import '../styles/globals.css'
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (

  <>
    <Head>
      <link rel="icon" href="/favicon.ico" />
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossOrigin="anonymous" />
      <link href="https://unpkg.com/tailwindcss@^2.0/dist/tailwind.min.css"
            rel="stylesheet" />
      <link rel="stylesheet" href="/styles.css"/>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
  <Component {...pageProps} />
  </>

  )

}
export default MyApp
